### PR TITLE
User interface with mock logic

### PR DESCRIPTION
**Pull request by tiagorahal**
# This pull request contains the following changes:
## * Add mock logic

### CODE REVIEW

**Review by BrianSammit — CHANGES_REQUESTED** [review]
CHANGES REQUIRED :red_circle: 
---------------
Hello, @tiagorahal  @Emmyn5600 You are doing an amazing job on this milestone. 
To highlight:
-You have a good naming on your code. :muscle: :100: 
However, there are a few changes to make :hammer_and_wrench: see them below :eyes: :point_down: 
---------------

- [x] Do not make any changes in config files - they represent style guidelines that you share with your team - which is a group of all Microverse students. Your Rubocop file is not like the original one. Please use the same file from [here](https://github.com/microverseinc/linters-config/blob/master/ruby/.rubocop.yml). 
- [x] The game allows me to keep playing with an empty input.  Please fix that. Write a validation so the game doesn't allow to continue playing if the input is empty. 
Screenshot from 2021-03-24 12-34-57

- [x] You write `Choose the letters between 1 and 9 to place your mark on the board
` but you are choosing numbers.  Please check the grammar. You can use Grammarly to check for errors. 
Screenshot from 2021-03-24 12-37-58

- [x] Game informs player if the selected move is invalid (without computing what an invalid move is). 
- [x] A loop is needed in this game. I recommend you use a `while` loop. The game must be finish till all positions are taken. 

```ruby
game_on = true

# initial instructions for player

while game_on
  # loop for each move

  if winner # and/or draw
    game_on = false
  end
end
```
Basic game flow implemented should include at least the steps present in the gif below: :point_down: 
game_flow_example
---------------
Please make the required changes and send it again for review :hammer_and_wrench: 
HAPPY CODING!!! :smile:

**Review by Dipeshtwis — CHANGES_REQUESTED** [review]
# Status:  ♻️ Changes Required ♻️
 Hi @tiagorahal   and @Emmyn5600, I'm Dipesh your reviewer for this PR 👩‍🚀 

Your Readme file is already looking great. 😊
It's good to see that you did some changes and took one step forward, but in-order to approve we have to work a little bit more.

## Always re-check if all the suggested changes applied or not.

## For Approval

- [x] Do not make any changes in config files - they represent style guidelines that you share with your team - which is a group of all Microverse students. Your Rubocop file is not like the original one. Please use the same file from [here](https://github.com/microverseinc/linters-config/blob/master/ruby/.rubocop.yml).

- [x] The game still allows me to keep playing with an empty input. Please fix that. Write a validation so the game doesn't allow to continue playing if the input is empty.

empty_input

## [Optional]

- [x] The time I choose the spot from the board, one warning came up on the terminal. I'm attaching the screenshot below.

warning

you can refer to this [link](https://github.com/rapid7/metasploit-framework/issues/13591) what's going on here? Fix it if you can figure it out.

Remember, This is optional and nothing to do with the project approval.

## Let's fix the required change, and we will be done.

(Feel free to contact me on slack by the handle of  **deep** if you have any additional question).
Happy Coding
[Dipesh Kumar](https://deeptwist.tk)
[Github](https://github.com/Dipeshtwis)

**Comment by tiagorahal** [comment]
# For the next reviewer :robot:
## "The final point of this milestone is to make sure that you thought about all actions needed to play Tic Tac Toe. It does not need to work yet - this will be done in the next milestone." - MICROVERSE

## According to Microverse the game does not need to work yet, that will be implemented on the next milestone

**Review by sinansevgi — APPROVED** [review]
# Status: Approved! ✅ 
----
Congratulations! 
----
Good job implementing the change as requested by the previous TSE.
You can now merge and submit.

Feel free to reach out to me on [slack](https://microverse-students.slack.com/team/U016UBBG4GZ)
----
### Sinan Sevgi

**Pull request closed without merging**
